# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mongo
    ports:
      - 27017:27017
    network_mode: "host" 


  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example

  node:
    build: 
      context: ../.
      dockerfile: ./enviroment/node.Dockerfile
    working_dir: /usr/src/app
    depends_on:
      - mongo
    command: bash -c  "sleep 30s && npm start"
    network_mode: "host" 
    ports:
      - 8088:8088
  
  client:
    build: 
      context: ../.
      dockerfile: ./enviroment/client.Dockerfile
    working_dir: /usr/src/app
    command: bash -c  "npm run dev"
    network_mode: "host" 
    ports:
      - 3030:3030
